pull_request_rules:
  - name: automatic merge when CI passes and 1 review
    conditions:
      - author=dependabot[bot]
      - "#approved-reviews-by>=1"
      - status-success=continuous-integration/travis-ci/pr
      - base=master
      - label!=work-in-progress
    actions:
      merge:
        method: merge
