pull_request_rules:
  - name: automatic merge on CI success and review
    conditions:
      - status-success=Travis CI - Pull Request
      - base=master
    actions:
      delete_head_branch: {}
      merge:
        method: merge
